// Autogenerated from Pigeon (v25.5.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}
bool _deepEquals(Object? a, Object? b) {
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
        .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    return a.length == b.length && a.entries.every((MapEntry<Object?, Object?> entry) =>
        (b as Map<Object?, Object?>).containsKey(entry.key) &&
        _deepEquals(entry.value, b[entry.key]));
  }
  return a == b;
}


enum StorageType {
  localFilesystem,
  s3,
  webdav,
  sftp,
  saf,
}

enum FileEntryType {
  file,
  directory,
  symlink,
  unknown,
}

enum RestoreState {
  idle,
  preparing,
  inProgress,
  completed,
  failed,
  cancelled,
}

class SourceInfo {
  SourceInfo({
    required this.host,
    required this.userName,
    required this.path,
  });

  String host;

  String userName;

  String path;

  List<Object?> _toList() {
    return <Object?>[
      host,
      userName,
      path,
    ];
  }

  Object encode() {
    return _toList();  }

  static SourceInfo decode(Object result) {
    result as List<Object?>;
    return SourceInfo(
      host: result[0]! as String,
      userName: result[1]! as String,
      path: result[2]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! SourceInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class SnapshotStats {
  SnapshotStats({
    required this.totalFileSize,
    required this.totalFileCount,
    required this.totalDirectoryCount,
  });

  int totalFileSize;

  int totalFileCount;

  int totalDirectoryCount;

  List<Object?> _toList() {
    return <Object?>[
      totalFileSize,
      totalFileCount,
      totalDirectoryCount,
    ];
  }

  Object encode() {
    return _toList();  }

  static SnapshotStats decode(Object result) {
    result as List<Object?>;
    return SnapshotStats(
      totalFileSize: result[0]! as int,
      totalFileCount: result[1]! as int,
      totalDirectoryCount: result[2]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! SnapshotStats || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class SnapshotInfo {
  SnapshotInfo({
    required this.id,
    required this.source,
    required this.startTimeEpochMs,
    this.endTimeEpochMs,
    required this.description,
    this.stats,
    required this.isIncomplete,
    required this.tags,
  });

  String id;

  SourceInfo source;

  int startTimeEpochMs;

  int? endTimeEpochMs;

  String description;

  SnapshotStats? stats;

  bool isIncomplete;

  Map<String?, String?> tags;

  List<Object?> _toList() {
    return <Object?>[
      id,
      source,
      startTimeEpochMs,
      endTimeEpochMs,
      description,
      stats,
      isIncomplete,
      tags,
    ];
  }

  Object encode() {
    return _toList();  }

  static SnapshotInfo decode(Object result) {
    result as List<Object?>;
    return SnapshotInfo(
      id: result[0]! as String,
      source: result[1]! as SourceInfo,
      startTimeEpochMs: result[2]! as int,
      endTimeEpochMs: result[3] as int?,
      description: result[4]! as String,
      stats: result[5] as SnapshotStats?,
      isIncomplete: result[6]! as bool,
      tags: (result[7] as Map<Object?, Object?>?)!.cast<String?, String?>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! SnapshotInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class FileEntry {
  FileEntry({
    required this.name,
    required this.type,
    required this.size,
    this.modTimeEpochMs,
    required this.permissions,
    this.objectId,
  });

  String name;

  FileEntryType type;

  int size;

  int? modTimeEpochMs;

  int permissions;

  String? objectId;

  List<Object?> _toList() {
    return <Object?>[
      name,
      type,
      size,
      modTimeEpochMs,
      permissions,
      objectId,
    ];
  }

  Object encode() {
    return _toList();  }

  static FileEntry decode(Object result) {
    result as List<Object?>;
    return FileEntry(
      name: result[0]! as String,
      type: result[1]! as FileEntryType,
      size: result[2]! as int,
      modTimeEpochMs: result[3] as int?,
      permissions: result[4]! as int,
      objectId: result[5] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! FileEntry || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class RestoreProgress {
  RestoreProgress({
    required this.state,
    required this.totalFiles,
    required this.restoredFiles,
    required this.totalBytes,
    required this.restoredBytes,
    this.currentFile,
    this.errorMessage,
  });

  RestoreState state;

  int totalFiles;

  int restoredFiles;

  int totalBytes;

  int restoredBytes;

  String? currentFile;

  String? errorMessage;

  List<Object?> _toList() {
    return <Object?>[
      state,
      totalFiles,
      restoredFiles,
      totalBytes,
      restoredBytes,
      currentFile,
      errorMessage,
    ];
  }

  Object encode() {
    return _toList();  }

  static RestoreProgress decode(Object result) {
    result as List<Object?>;
    return RestoreProgress(
      state: result[0]! as RestoreState,
      totalFiles: result[1]! as int,
      restoredFiles: result[2]! as int,
      totalBytes: result[3]! as int,
      restoredBytes: result[4]! as int,
      currentFile: result[5] as String?,
      errorMessage: result[6] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RestoreProgress || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class LocalFilesystemConfig {
  LocalFilesystemConfig({
    required this.path,
  });

  String path;

  List<Object?> _toList() {
    return <Object?>[
      path,
    ];
  }

  Object encode() {
    return _toList();  }

  static LocalFilesystemConfig decode(Object result) {
    result as List<Object?>;
    return LocalFilesystemConfig(
      path: result[0]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! LocalFilesystemConfig || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class S3Config {
  S3Config({
    required this.bucket,
    required this.endpoint,
    required this.region,
    required this.accessKeyId,
  });

  String bucket;

  String endpoint;

  String region;

  String accessKeyId;

  List<Object?> _toList() {
    return <Object?>[
      bucket,
      endpoint,
      region,
      accessKeyId,
    ];
  }

  Object encode() {
    return _toList();  }

  static S3Config decode(Object result) {
    result as List<Object?>;
    return S3Config(
      bucket: result[0]! as String,
      endpoint: result[1]! as String,
      region: result[2]! as String,
      accessKeyId: result[3]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! S3Config || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class WebDavConfig {
  WebDavConfig({
    required this.url,
    required this.username,
  });

  String url;

  String username;

  List<Object?> _toList() {
    return <Object?>[
      url,
      username,
    ];
  }

  Object encode() {
    return _toList();  }

  static WebDavConfig decode(Object result) {
    result as List<Object?>;
    return WebDavConfig(
      url: result[0]! as String,
      username: result[1]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! WebDavConfig || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class SftpConfig {
  SftpConfig({
    required this.host,
    required this.port,
    required this.username,
    required this.path,
  });

  String host;

  int port;

  String username;

  String path;

  List<Object?> _toList() {
    return <Object?>[
      host,
      port,
      username,
      path,
    ];
  }

  Object encode() {
    return _toList();  }

  static SftpConfig decode(Object result) {
    result as List<Object?>;
    return SftpConfig(
      host: result[0]! as String,
      port: result[1]! as int,
      username: result[2]! as String,
      path: result[3]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! SftpConfig || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class SafConfig {
  SafConfig({
    required this.treeUri,
    required this.displayPath,
  });

  String treeUri;

  String displayPath;

  List<Object?> _toList() {
    return <Object?>[
      treeUri,
      displayPath,
    ];
  }

  Object encode() {
    return _toList();  }

  static SafConfig decode(Object result) {
    result as List<Object?>;
    return SafConfig(
      treeUri: result[0]! as String,
      displayPath: result[1]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! SafConfig || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class ConnectionConfig {
  ConnectionConfig({
    required this.storageType,
    this.local,
    this.s3,
    this.webdav,
    this.sftp,
    this.saf,
  });

  StorageType storageType;

  LocalFilesystemConfig? local;

  S3Config? s3;

  WebDavConfig? webdav;

  SftpConfig? sftp;

  SafConfig? saf;

  List<Object?> _toList() {
    return <Object?>[
      storageType,
      local,
      s3,
      webdav,
      sftp,
      saf,
    ];
  }

  Object encode() {
    return _toList();  }

  static ConnectionConfig decode(Object result) {
    result as List<Object?>;
    return ConnectionConfig(
      storageType: result[0]! as StorageType,
      local: result[1] as LocalFilesystemConfig?,
      s3: result[2] as S3Config?,
      webdav: result[3] as WebDavConfig?,
      sftp: result[4] as SftpConfig?,
      saf: result[5] as SafConfig?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ConnectionConfig || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class RepositoryConnection {
  RepositoryConnection({
    required this.id,
    required this.displayName,
    required this.storageType,
    required this.connectionConfig,
    this.lastConnectedEpochMs,
    required this.isConnected,
  });

  String id;

  String displayName;

  StorageType storageType;

  ConnectionConfig connectionConfig;

  int? lastConnectedEpochMs;

  bool isConnected;

  List<Object?> _toList() {
    return <Object?>[
      id,
      displayName,
      storageType,
      connectionConfig,
      lastConnectedEpochMs,
      isConnected,
    ];
  }

  Object encode() {
    return _toList();  }

  static RepositoryConnection decode(Object result) {
    result as List<Object?>;
    return RepositoryConnection(
      id: result[0]! as String,
      displayName: result[1]! as String,
      storageType: result[2]! as StorageType,
      connectionConfig: result[3]! as ConnectionConfig,
      lastConnectedEpochMs: result[4] as int?,
      isConnected: result[5]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RepositoryConnection || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class RestoreOptions {
  RestoreOptions({
    required this.parallel,
    required this.incremental,
    required this.overwriteExisting,
  });

  int parallel;

  bool incremental;

  bool overwriteExisting;

  List<Object?> _toList() {
    return <Object?>[
      parallel,
      incremental,
      overwriteExisting,
    ];
  }

  Object encode() {
    return _toList();  }

  static RestoreOptions decode(Object result) {
    result as List<Object?>;
    return RestoreOptions(
      parallel: result[0]! as int,
      incremental: result[1]! as bool,
      overwriteExisting: result[2]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RestoreOptions || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class ConnectRequest {
  ConnectRequest({
    required this.config,
    required this.password,
    required this.savePassword,
  });

  ConnectionConfig config;

  String password;

  bool savePassword;

  List<Object?> _toList() {
    return <Object?>[
      config,
      password,
      savePassword,
    ];
  }

  Object encode() {
    return _toList();  }

  static ConnectRequest decode(Object result) {
    result as List<Object?>;
    return ConnectRequest(
      config: result[0]! as ConnectionConfig,
      password: result[1]! as String,
      savePassword: result[2]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ConnectRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class SnapshotListRequest {
  SnapshotListRequest({
    this.source,
  });

  SourceInfo? source;

  List<Object?> _toList() {
    return <Object?>[
      source,
    ];
  }

  Object encode() {
    return _toList();  }

  static SnapshotListRequest decode(Object result) {
    result as List<Object?>;
    return SnapshotListRequest(
      source: result[0] as SourceInfo?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! SnapshotListRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class ListDirectoryRequest {
  ListDirectoryRequest({
    required this.snapshotId,
    required this.path,
    this.pageSize,
    this.pageToken,
  });

  String snapshotId;

  String path;

  int? pageSize;

  String? pageToken;

  List<Object?> _toList() {
    return <Object?>[
      snapshotId,
      path,
      pageSize,
      pageToken,
    ];
  }

  Object encode() {
    return _toList();  }

  static ListDirectoryRequest decode(Object result) {
    result as List<Object?>;
    return ListDirectoryRequest(
      snapshotId: result[0]! as String,
      path: result[1]! as String,
      pageSize: result[2] as int?,
      pageToken: result[3] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ListDirectoryRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class DirectoryPage {
  DirectoryPage({
    required this.entries,
    this.nextPageToken,
  });

  List<FileEntry?> entries;

  String? nextPageToken;

  List<Object?> _toList() {
    return <Object?>[
      entries,
      nextPageToken,
    ];
  }

  Object encode() {
    return _toList();  }

  static DirectoryPage decode(Object result) {
    result as List<Object?>;
    return DirectoryPage(
      entries: (result[0] as List<Object?>?)!.cast<FileEntry?>(),
      nextPageToken: result[1] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! DirectoryPage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class RestoreRequest {
  RestoreRequest({
    required this.snapshotId,
    required this.sourcePath,
    required this.destinationUri,
    this.options,
  });

  String snapshotId;

  String sourcePath;

  String destinationUri;

  RestoreOptions? options;

  List<Object?> _toList() {
    return <Object?>[
      snapshotId,
      sourcePath,
      destinationUri,
      options,
    ];
  }

  Object encode() {
    return _toList();  }

  static RestoreRequest decode(Object result) {
    result as List<Object?>;
    return RestoreRequest(
      snapshotId: result[0]! as String,
      sourcePath: result[1]! as String,
      destinationUri: result[2]! as String,
      options: result[3] as RestoreOptions?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RestoreRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class SafPickResult {
  SafPickResult({
    this.uri,
    this.displayName,
  });

  String? uri;

  String? displayName;

  List<Object?> _toList() {
    return <Object?>[
      uri,
      displayName,
    ];
  }

  Object encode() {
    return _toList();  }

  static SafPickResult decode(Object result) {
    result as List<Object?>;
    return SafPickResult(
      uri: result[0] as String?,
      displayName: result[1] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! SafPickResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class PersistUriPermissionRequest {
  PersistUriPermissionRequest({
    required this.uri,
    required this.read,
    required this.write,
  });

  String uri;

  bool read;

  bool write;

  List<Object?> _toList() {
    return <Object?>[
      uri,
      read,
      write,
    ];
  }

  Object encode() {
    return _toList();  }

  static PersistUriPermissionRequest decode(Object result) {
    result as List<Object?>;
    return PersistUriPermissionRequest(
      uri: result[0]! as String,
      read: result[1]! as bool,
      write: result[2]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PersistUriPermissionRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is StorageType) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is FileEntryType) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is RestoreState) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    }    else if (value is SourceInfo) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is SnapshotStats) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is SnapshotInfo) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    }    else if (value is FileEntry) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    }    else if (value is RestoreProgress) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    }    else if (value is LocalFilesystemConfig) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    }    else if (value is S3Config) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    }    else if (value is WebDavConfig) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    }    else if (value is SftpConfig) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    }    else if (value is SafConfig) {
      buffer.putUint8(141);
      writeValue(buffer, value.encode());
    }    else if (value is ConnectionConfig) {
      buffer.putUint8(142);
      writeValue(buffer, value.encode());
    }    else if (value is RepositoryConnection) {
      buffer.putUint8(143);
      writeValue(buffer, value.encode());
    }    else if (value is RestoreOptions) {
      buffer.putUint8(144);
      writeValue(buffer, value.encode());
    }    else if (value is ConnectRequest) {
      buffer.putUint8(145);
      writeValue(buffer, value.encode());
    }    else if (value is SnapshotListRequest) {
      buffer.putUint8(146);
      writeValue(buffer, value.encode());
    }    else if (value is ListDirectoryRequest) {
      buffer.putUint8(147);
      writeValue(buffer, value.encode());
    }    else if (value is DirectoryPage) {
      buffer.putUint8(148);
      writeValue(buffer, value.encode());
    }    else if (value is RestoreRequest) {
      buffer.putUint8(149);
      writeValue(buffer, value.encode());
    }    else if (value is SafPickResult) {
      buffer.putUint8(150);
      writeValue(buffer, value.encode());
    }    else if (value is PersistUriPermissionRequest) {
      buffer.putUint8(151);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : StorageType.values[value];
      case 130: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : FileEntryType.values[value];
      case 131: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : RestoreState.values[value];
      case 132: 
        return SourceInfo.decode(readValue(buffer)!);
      case 133: 
        return SnapshotStats.decode(readValue(buffer)!);
      case 134: 
        return SnapshotInfo.decode(readValue(buffer)!);
      case 135: 
        return FileEntry.decode(readValue(buffer)!);
      case 136: 
        return RestoreProgress.decode(readValue(buffer)!);
      case 137: 
        return LocalFilesystemConfig.decode(readValue(buffer)!);
      case 138: 
        return S3Config.decode(readValue(buffer)!);
      case 139: 
        return WebDavConfig.decode(readValue(buffer)!);
      case 140: 
        return SftpConfig.decode(readValue(buffer)!);
      case 141: 
        return SafConfig.decode(readValue(buffer)!);
      case 142: 
        return ConnectionConfig.decode(readValue(buffer)!);
      case 143: 
        return RepositoryConnection.decode(readValue(buffer)!);
      case 144: 
        return RestoreOptions.decode(readValue(buffer)!);
      case 145: 
        return ConnectRequest.decode(readValue(buffer)!);
      case 146: 
        return SnapshotListRequest.decode(readValue(buffer)!);
      case 147: 
        return ListDirectoryRequest.decode(readValue(buffer)!);
      case 148: 
        return DirectoryPage.decode(readValue(buffer)!);
      case 149: 
        return RestoreRequest.decode(readValue(buffer)!);
      case 150: 
        return SafPickResult.decode(readValue(buffer)!);
      case 151: 
        return PersistUriPermissionRequest.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class KopiaHostApi {
  /// Constructor for [KopiaHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  KopiaHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Simple ping method to verify bridge communication.
  /// Returns "pong" if the bridge is working correctly.
  Future<String> ping() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_ui.KopiaHostApi.ping$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as String?)!;
    }
  }

  Future<RepositoryConnection> connect(ConnectRequest request) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_ui.KopiaHostApi.connect$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as RepositoryConnection?)!;
    }
  }

  Future<void> disconnect() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_ui.KopiaHostApi.disconnect$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<List<SourceInfo?>> listSources() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_ui.KopiaHostApi.listSources$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as List<Object?>?)!.cast<SourceInfo?>();
    }
  }

  Future<List<SnapshotInfo?>> listSnapshots(SnapshotListRequest request) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_ui.KopiaHostApi.listSnapshots$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as List<Object?>?)!.cast<SnapshotInfo?>();
    }
  }

  Future<SnapshotInfo?> getSnapshot(String snapshotId) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_ui.KopiaHostApi.getSnapshot$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[snapshotId]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return (pigeonVar_replyList[0] as SnapshotInfo?);
    }
  }

  Future<DirectoryPage> listDirectory(ListDirectoryRequest request) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_ui.KopiaHostApi.listDirectory$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as DirectoryPage?)!;
    }
  }

  Future<void> startRestore(RestoreRequest request) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_ui.KopiaHostApi.startRestore$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> cancelRestore() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_ui.KopiaHostApi.cancelRestore$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<SafPickResult> pickRestoreDestination() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_ui.KopiaHostApi.pickRestoreDestination$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as SafPickResult?)!;
    }
  }

  Future<void> persistUriPermission(PersistUriPermissionRequest request) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_ui.KopiaHostApi.persistUriPermission$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }
}
