// Autogenerated from Pigeon (v25.5.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package org.kopiaKt.app.bridge

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object KopiaBridgePigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).containsKey(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

enum class StorageType(val raw: Int) {
  LOCAL_FILESYSTEM(0),
  S3(1),
  WEBDAV(2),
  SFTP(3),
  SAF(4);

  companion object {
    fun ofRaw(raw: Int): StorageType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class FileEntryType(val raw: Int) {
  FILE(0),
  DIRECTORY(1),
  SYMLINK(2),
  UNKNOWN(3);

  companion object {
    fun ofRaw(raw: Int): FileEntryType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class RestoreState(val raw: Int) {
  IDLE(0),
  PREPARING(1),
  IN_PROGRESS(2),
  COMPLETED(3),
  FAILED(4),
  CANCELLED(5);

  companion object {
    fun ofRaw(raw: Int): RestoreState? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class SourceInfo (
  val host: String,
  val userName: String,
  val path: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SourceInfo {
      val host = pigeonVar_list[0] as String
      val userName = pigeonVar_list[1] as String
      val path = pigeonVar_list[2] as String
      return SourceInfo(host, userName, path)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      host,
      userName,
      path,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is SourceInfo) {
      return false
    }
    if (this === other) {
      return true
    }
    return KopiaBridgePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class SnapshotStats (
  val totalFileSize: Long,
  val totalFileCount: Long,
  val totalDirectoryCount: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SnapshotStats {
      val totalFileSize = pigeonVar_list[0] as Long
      val totalFileCount = pigeonVar_list[1] as Long
      val totalDirectoryCount = pigeonVar_list[2] as Long
      return SnapshotStats(totalFileSize, totalFileCount, totalDirectoryCount)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      totalFileSize,
      totalFileCount,
      totalDirectoryCount,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is SnapshotStats) {
      return false
    }
    if (this === other) {
      return true
    }
    return KopiaBridgePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class SnapshotInfo (
  val id: String,
  val source: SourceInfo,
  val startTimeEpochMs: Long,
  val endTimeEpochMs: Long? = null,
  val description: String,
  val stats: SnapshotStats? = null,
  val isIncomplete: Boolean,
  val tags: Map<String?, String?>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SnapshotInfo {
      val id = pigeonVar_list[0] as String
      val source = pigeonVar_list[1] as SourceInfo
      val startTimeEpochMs = pigeonVar_list[2] as Long
      val endTimeEpochMs = pigeonVar_list[3] as Long?
      val description = pigeonVar_list[4] as String
      val stats = pigeonVar_list[5] as SnapshotStats?
      val isIncomplete = pigeonVar_list[6] as Boolean
      val tags = pigeonVar_list[7] as Map<String?, String?>
      return SnapshotInfo(id, source, startTimeEpochMs, endTimeEpochMs, description, stats, isIncomplete, tags)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      source,
      startTimeEpochMs,
      endTimeEpochMs,
      description,
      stats,
      isIncomplete,
      tags,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is SnapshotInfo) {
      return false
    }
    if (this === other) {
      return true
    }
    return KopiaBridgePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class FileEntry (
  val name: String,
  val type: FileEntryType,
  val size: Long,
  val modTimeEpochMs: Long? = null,
  val permissions: Long,
  val objectId: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): FileEntry {
      val name = pigeonVar_list[0] as String
      val type = pigeonVar_list[1] as FileEntryType
      val size = pigeonVar_list[2] as Long
      val modTimeEpochMs = pigeonVar_list[3] as Long?
      val permissions = pigeonVar_list[4] as Long
      val objectId = pigeonVar_list[5] as String?
      return FileEntry(name, type, size, modTimeEpochMs, permissions, objectId)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      name,
      type,
      size,
      modTimeEpochMs,
      permissions,
      objectId,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is FileEntry) {
      return false
    }
    if (this === other) {
      return true
    }
    return KopiaBridgePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class RestoreProgress (
  val state: RestoreState,
  val totalFiles: Long,
  val restoredFiles: Long,
  val totalBytes: Long,
  val restoredBytes: Long,
  val currentFile: String? = null,
  val errorMessage: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RestoreProgress {
      val state = pigeonVar_list[0] as RestoreState
      val totalFiles = pigeonVar_list[1] as Long
      val restoredFiles = pigeonVar_list[2] as Long
      val totalBytes = pigeonVar_list[3] as Long
      val restoredBytes = pigeonVar_list[4] as Long
      val currentFile = pigeonVar_list[5] as String?
      val errorMessage = pigeonVar_list[6] as String?
      return RestoreProgress(state, totalFiles, restoredFiles, totalBytes, restoredBytes, currentFile, errorMessage)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      state,
      totalFiles,
      restoredFiles,
      totalBytes,
      restoredBytes,
      currentFile,
      errorMessage,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is RestoreProgress) {
      return false
    }
    if (this === other) {
      return true
    }
    return KopiaBridgePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class LocalFilesystemConfig (
  val path: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LocalFilesystemConfig {
      val path = pigeonVar_list[0] as String
      return LocalFilesystemConfig(path)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      path,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is LocalFilesystemConfig) {
      return false
    }
    if (this === other) {
      return true
    }
    return KopiaBridgePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class S3Config (
  val bucket: String,
  val endpoint: String,
  val region: String,
  val accessKeyId: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): S3Config {
      val bucket = pigeonVar_list[0] as String
      val endpoint = pigeonVar_list[1] as String
      val region = pigeonVar_list[2] as String
      val accessKeyId = pigeonVar_list[3] as String
      return S3Config(bucket, endpoint, region, accessKeyId)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      bucket,
      endpoint,
      region,
      accessKeyId,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is S3Config) {
      return false
    }
    if (this === other) {
      return true
    }
    return KopiaBridgePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class WebDavConfig (
  val url: String,
  val username: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): WebDavConfig {
      val url = pigeonVar_list[0] as String
      val username = pigeonVar_list[1] as String
      return WebDavConfig(url, username)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      url,
      username,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is WebDavConfig) {
      return false
    }
    if (this === other) {
      return true
    }
    return KopiaBridgePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class SftpConfig (
  val host: String,
  val port: Long,
  val username: String,
  val path: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SftpConfig {
      val host = pigeonVar_list[0] as String
      val port = pigeonVar_list[1] as Long
      val username = pigeonVar_list[2] as String
      val path = pigeonVar_list[3] as String
      return SftpConfig(host, port, username, path)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      host,
      port,
      username,
      path,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is SftpConfig) {
      return false
    }
    if (this === other) {
      return true
    }
    return KopiaBridgePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class SafConfig (
  val treeUri: String,
  val displayPath: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SafConfig {
      val treeUri = pigeonVar_list[0] as String
      val displayPath = pigeonVar_list[1] as String
      return SafConfig(treeUri, displayPath)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      treeUri,
      displayPath,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is SafConfig) {
      return false
    }
    if (this === other) {
      return true
    }
    return KopiaBridgePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ConnectionConfig (
  val storageType: StorageType,
  val local: LocalFilesystemConfig? = null,
  val s3: S3Config? = null,
  val webdav: WebDavConfig? = null,
  val sftp: SftpConfig? = null,
  val saf: SafConfig? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ConnectionConfig {
      val storageType = pigeonVar_list[0] as StorageType
      val local = pigeonVar_list[1] as LocalFilesystemConfig?
      val s3 = pigeonVar_list[2] as S3Config?
      val webdav = pigeonVar_list[3] as WebDavConfig?
      val sftp = pigeonVar_list[4] as SftpConfig?
      val saf = pigeonVar_list[5] as SafConfig?
      return ConnectionConfig(storageType, local, s3, webdav, sftp, saf)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      storageType,
      local,
      s3,
      webdav,
      sftp,
      saf,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is ConnectionConfig) {
      return false
    }
    if (this === other) {
      return true
    }
    return KopiaBridgePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class RepositoryConnection (
  val id: String,
  val displayName: String,
  val storageType: StorageType,
  val connectionConfig: ConnectionConfig,
  val lastConnectedEpochMs: Long? = null,
  val isConnected: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RepositoryConnection {
      val id = pigeonVar_list[0] as String
      val displayName = pigeonVar_list[1] as String
      val storageType = pigeonVar_list[2] as StorageType
      val connectionConfig = pigeonVar_list[3] as ConnectionConfig
      val lastConnectedEpochMs = pigeonVar_list[4] as Long?
      val isConnected = pigeonVar_list[5] as Boolean
      return RepositoryConnection(id, displayName, storageType, connectionConfig, lastConnectedEpochMs, isConnected)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      displayName,
      storageType,
      connectionConfig,
      lastConnectedEpochMs,
      isConnected,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is RepositoryConnection) {
      return false
    }
    if (this === other) {
      return true
    }
    return KopiaBridgePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class RestoreOptions (
  val parallel: Long,
  val incremental: Boolean,
  val overwriteExisting: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RestoreOptions {
      val parallel = pigeonVar_list[0] as Long
      val incremental = pigeonVar_list[1] as Boolean
      val overwriteExisting = pigeonVar_list[2] as Boolean
      return RestoreOptions(parallel, incremental, overwriteExisting)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      parallel,
      incremental,
      overwriteExisting,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is RestoreOptions) {
      return false
    }
    if (this === other) {
      return true
    }
    return KopiaBridgePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ConnectRequest (
  val config: ConnectionConfig,
  val password: String,
  val savePassword: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ConnectRequest {
      val config = pigeonVar_list[0] as ConnectionConfig
      val password = pigeonVar_list[1] as String
      val savePassword = pigeonVar_list[2] as Boolean
      return ConnectRequest(config, password, savePassword)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      config,
      password,
      savePassword,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is ConnectRequest) {
      return false
    }
    if (this === other) {
      return true
    }
    return KopiaBridgePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class SnapshotListRequest (
  val source: SourceInfo? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SnapshotListRequest {
      val source = pigeonVar_list[0] as SourceInfo?
      return SnapshotListRequest(source)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      source,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is SnapshotListRequest) {
      return false
    }
    if (this === other) {
      return true
    }
    return KopiaBridgePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ListDirectoryRequest (
  val snapshotId: String,
  val path: String,
  val pageSize: Long? = null,
  val pageToken: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ListDirectoryRequest {
      val snapshotId = pigeonVar_list[0] as String
      val path = pigeonVar_list[1] as String
      val pageSize = pigeonVar_list[2] as Long?
      val pageToken = pigeonVar_list[3] as String?
      return ListDirectoryRequest(snapshotId, path, pageSize, pageToken)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      snapshotId,
      path,
      pageSize,
      pageToken,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is ListDirectoryRequest) {
      return false
    }
    if (this === other) {
      return true
    }
    return KopiaBridgePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class DirectoryPage (
  val entries: List<FileEntry?>,
  val nextPageToken: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DirectoryPage {
      val entries = pigeonVar_list[0] as List<FileEntry?>
      val nextPageToken = pigeonVar_list[1] as String?
      return DirectoryPage(entries, nextPageToken)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      entries,
      nextPageToken,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is DirectoryPage) {
      return false
    }
    if (this === other) {
      return true
    }
    return KopiaBridgePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class RestoreRequest (
  val snapshotId: String,
  val sourcePath: String,
  val destinationUri: String,
  val options: RestoreOptions? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RestoreRequest {
      val snapshotId = pigeonVar_list[0] as String
      val sourcePath = pigeonVar_list[1] as String
      val destinationUri = pigeonVar_list[2] as String
      val options = pigeonVar_list[3] as RestoreOptions?
      return RestoreRequest(snapshotId, sourcePath, destinationUri, options)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      snapshotId,
      sourcePath,
      destinationUri,
      options,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is RestoreRequest) {
      return false
    }
    if (this === other) {
      return true
    }
    return KopiaBridgePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class SafPickResult (
  val uri: String? = null,
  val displayName: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SafPickResult {
      val uri = pigeonVar_list[0] as String?
      val displayName = pigeonVar_list[1] as String?
      return SafPickResult(uri, displayName)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      uri,
      displayName,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is SafPickResult) {
      return false
    }
    if (this === other) {
      return true
    }
    return KopiaBridgePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PersistUriPermissionRequest (
  val uri: String,
  val read: Boolean,
  val write: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PersistUriPermissionRequest {
      val uri = pigeonVar_list[0] as String
      val read = pigeonVar_list[1] as Boolean
      val write = pigeonVar_list[2] as Boolean
      return PersistUriPermissionRequest(uri, read, write)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      uri,
      read,
      write,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is PersistUriPermissionRequest) {
      return false
    }
    if (this === other) {
      return true
    }
    return KopiaBridgePigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class KopiaBridgePigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          StorageType.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          FileEntryType.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          RestoreState.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SourceInfo.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SnapshotStats.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SnapshotInfo.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          FileEntry.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RestoreProgress.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LocalFilesystemConfig.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          S3Config.fromList(it)
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          WebDavConfig.fromList(it)
        }
      }
      140.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SftpConfig.fromList(it)
        }
      }
      141.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SafConfig.fromList(it)
        }
      }
      142.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ConnectionConfig.fromList(it)
        }
      }
      143.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RepositoryConnection.fromList(it)
        }
      }
      144.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RestoreOptions.fromList(it)
        }
      }
      145.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ConnectRequest.fromList(it)
        }
      }
      146.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SnapshotListRequest.fromList(it)
        }
      }
      147.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ListDirectoryRequest.fromList(it)
        }
      }
      148.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DirectoryPage.fromList(it)
        }
      }
      149.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RestoreRequest.fromList(it)
        }
      }
      150.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SafPickResult.fromList(it)
        }
      }
      151.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PersistUriPermissionRequest.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is StorageType -> {
        stream.write(129)
        writeValue(stream, value.raw)
      }
      is FileEntryType -> {
        stream.write(130)
        writeValue(stream, value.raw)
      }
      is RestoreState -> {
        stream.write(131)
        writeValue(stream, value.raw)
      }
      is SourceInfo -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is SnapshotStats -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is SnapshotInfo -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is FileEntry -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is RestoreProgress -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is LocalFilesystemConfig -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is S3Config -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is WebDavConfig -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      is SftpConfig -> {
        stream.write(140)
        writeValue(stream, value.toList())
      }
      is SafConfig -> {
        stream.write(141)
        writeValue(stream, value.toList())
      }
      is ConnectionConfig -> {
        stream.write(142)
        writeValue(stream, value.toList())
      }
      is RepositoryConnection -> {
        stream.write(143)
        writeValue(stream, value.toList())
      }
      is RestoreOptions -> {
        stream.write(144)
        writeValue(stream, value.toList())
      }
      is ConnectRequest -> {
        stream.write(145)
        writeValue(stream, value.toList())
      }
      is SnapshotListRequest -> {
        stream.write(146)
        writeValue(stream, value.toList())
      }
      is ListDirectoryRequest -> {
        stream.write(147)
        writeValue(stream, value.toList())
      }
      is DirectoryPage -> {
        stream.write(148)
        writeValue(stream, value.toList())
      }
      is RestoreRequest -> {
        stream.write(149)
        writeValue(stream, value.toList())
      }
      is SafPickResult -> {
        stream.write(150)
        writeValue(stream, value.toList())
      }
      is PersistUriPermissionRequest -> {
        stream.write(151)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface KopiaHostApi {
  /**
   * Simple ping method to verify bridge communication.
   * Returns "pong" if the bridge is working correctly.
   */
  fun ping(callback: (Result<String>) -> Unit)
  fun connect(request: ConnectRequest, callback: (Result<RepositoryConnection>) -> Unit)
  fun disconnect(callback: (Result<Unit>) -> Unit)
  fun listSources(callback: (Result<List<SourceInfo?>>) -> Unit)
  fun listSnapshots(request: SnapshotListRequest, callback: (Result<List<SnapshotInfo?>>) -> Unit)
  fun getSnapshot(snapshotId: String, callback: (Result<SnapshotInfo?>) -> Unit)
  fun listDirectory(request: ListDirectoryRequest, callback: (Result<DirectoryPage>) -> Unit)
  fun startRestore(request: RestoreRequest, callback: (Result<Unit>) -> Unit)
  fun cancelRestore(callback: (Result<Unit>) -> Unit)
  fun pickRestoreDestination(callback: (Result<SafPickResult>) -> Unit)
  fun persistUriPermission(request: PersistUriPermissionRequest, callback: (Result<Unit>) -> Unit)

  companion object {
    /** The codec used by KopiaHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      KopiaBridgePigeonCodec()
    }
    /** Sets up an instance of `KopiaHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: KopiaHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_ui.KopiaHostApi.ping$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.ping{ result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(KopiaBridgePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(KopiaBridgePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_ui.KopiaHostApi.connect$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as ConnectRequest
            api.connect(requestArg) { result: Result<RepositoryConnection> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(KopiaBridgePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(KopiaBridgePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_ui.KopiaHostApi.disconnect$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.disconnect{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(KopiaBridgePigeonUtils.wrapError(error))
              } else {
                reply.reply(KopiaBridgePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_ui.KopiaHostApi.listSources$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.listSources{ result: Result<List<SourceInfo?>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(KopiaBridgePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(KopiaBridgePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_ui.KopiaHostApi.listSnapshots$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as SnapshotListRequest
            api.listSnapshots(requestArg) { result: Result<List<SnapshotInfo?>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(KopiaBridgePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(KopiaBridgePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_ui.KopiaHostApi.getSnapshot$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val snapshotIdArg = args[0] as String
            api.getSnapshot(snapshotIdArg) { result: Result<SnapshotInfo?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(KopiaBridgePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(KopiaBridgePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_ui.KopiaHostApi.listDirectory$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as ListDirectoryRequest
            api.listDirectory(requestArg) { result: Result<DirectoryPage> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(KopiaBridgePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(KopiaBridgePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_ui.KopiaHostApi.startRestore$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as RestoreRequest
            api.startRestore(requestArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(KopiaBridgePigeonUtils.wrapError(error))
              } else {
                reply.reply(KopiaBridgePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_ui.KopiaHostApi.cancelRestore$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.cancelRestore{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(KopiaBridgePigeonUtils.wrapError(error))
              } else {
                reply.reply(KopiaBridgePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_ui.KopiaHostApi.pickRestoreDestination$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.pickRestoreDestination{ result: Result<SafPickResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(KopiaBridgePigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(KopiaBridgePigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_ui.KopiaHostApi.persistUriPermission$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as PersistUriPermissionRequest
            api.persistUriPermission(requestArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(KopiaBridgePigeonUtils.wrapError(error))
              } else {
                reply.reply(KopiaBridgePigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
